services:
  5e:
    container_name: 5e
    image: JCCriv76/5e
    volumes:
      - ~/5etools-docker/htdocs:/usr/local/apache2/htdocs
    ports:
     - 5050:80/tcp
    environment:
     - IMG=TRUE # Set to TRUE to pull images from https://github.com/5etools-mirror-2/5etools-img (as a Git submodule)
