services:
  5e:
    container_name: 5e
    image: JCCriv76/5e
    volumes:
      - ~/5etools-docker/htdocs:/usr/local/apache2/htdocs
    ports:
     - 5050:80/tcp
    environment:
     - IMG=TRUE
    restart: unless-stopped
